// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv3a7qadtc5I4K3zfzdWzd2tRynBsnJfU',
    appId: '1:498508813313:web:a4fa77d99bd64fcf325c00',
    messagingSenderId: '498508813313',
    projectId: 'city-89a1f',
    authDomain: 'city-89a1f.firebaseapp.com',
    databaseURL: 'https://city-89a1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'city-89a1f.firebasestorage.app',
    measurementId: 'G-HBD867H40K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtEntKEnxEWhMl20D4QL5RnOoa_yCwVRw',
    appId: '1:498508813313:android:492d1d19731af13d325c00',
    messagingSenderId: '498508813313',
    projectId: 'city-89a1f',
    databaseURL: 'https://city-89a1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'city-89a1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSPzOwdoI4qH7PYeY3_ajS2pQmyt4j-2c',
    appId: '1:498508813313:ios:90e626b7759f9f52325c00',
    messagingSenderId: '498508813313',
    projectId: 'city-89a1f',
    databaseURL: 'https://city-89a1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'city-89a1f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSPzOwdoI4qH7PYeY3_ajS2pQmyt4j-2c',
    appId: '1:498508813313:ios:90e626b7759f9f52325c00',
    messagingSenderId: '498508813313',
    projectId: 'city-89a1f',
    databaseURL: 'https://city-89a1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'city-89a1f.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv3a7qadtc5I4K3zfzdWzd2tRynBsnJfU',
    appId: '1:498508813313:web:c51861e4c261aed2325c00',
    messagingSenderId: '498508813313',
    projectId: 'city-89a1f',
    authDomain: 'city-89a1f.firebaseapp.com',
    databaseURL: 'https://city-89a1f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'city-89a1f.firebasestorage.app',
    measurementId: 'G-NDTDPKK9ZE',
  );
}
